{
 "title": "Smart City Energy Monitoring (HITL)",
 "tags": [
  "smartcity",
  "energy",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Traffic Masuk Gateway (Real-time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"api-gateway\"}[5m])",
     "legendFormat": "API Gateway Load"
    }
   ]
  },
  {
   "title": "Beban Antrean RabbitMQ (Grid Data)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"grid.new\"}",
     "legendFormat": "Grid Messages"
    }
   ]
  },
  {
   "title": "Deteksi Korsleting (Machine Learning)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(anomaly_detections_total{job=\"python-ml\"})",
     "legendFormat": "Anomali Fisik"
    }
   ]
  }
 ]
}