apiVersion: v1
kind: Secret
metadata:
  name: smartcity-secrets
  namespace: smartcity-energy-management-system
type: Opaque
stringData:
  JWT_SECRET: "rahasia_smartcity_2026_kelompok_5"
  DB_PASS: "rootpass"